import root
import prime
import key
li=[]
print("give the range in which you want prime numbers")
print("start=",end=" ")
lower=int(input())
print("last=",end=" ")
print("should no exceed 1024",end=" ")
upper=int(input())
print("prime between",lower,"and",upper,"are:")
for num in range(lower,upper):
    if(prime.isprime(num)):
        print(num,end=" ")
        li.append(num)
print()
print("select a prime",end=" ")
q=int(input())
if q not in li:
    f1=1
    while(f1):
        if q not in li:
            print("please select the prime number from  below list only")
            print(li)
            q=int(input())
            if q in li:
                f1=0
print("primitive roots list")
li=[]
print("enter lower and upper limits of primitive roots")
print("upper limit should not execeed  "+str(q))
lower=int(input())
upper=int(input())
print("k")
for k in range(lower,upper):
    c=root.root(k,q)
    if(c is not 0):
        print(c,end=" ")
        li.append(c)
print()
print("selct root ",end=" ")
a=int(input())
if a not in li:
    f1=1
    while(f1):
        if a not in li:
            print("please select the root from below list only")
            print(li)
            a=int(input())
            if a in li:
                f1=0

print("Aggreed prime is",q,"and root is",a)

print("enter a secret value of the alice",end=" ")
pia=int(input())
if pia not in range(1,q):
    f1=1
    while(f1):
        if pia not in range(1,q):
            print("please select in range",1,"and",q)
            pia=int(input())
            if pia in range(1,q):
                f1=0
pua=key.kg(pia,a,q)
print()
print("public of alice",pua)

print("enter a secret value of the bob",end=" ")
pib=int(input())
if pib not in range(1,q):
    f1=1
    while(f1):
        if pib not in range(1,q):
            print("please select in range",1,"and",q)
            pib=int(input())
            if pib in range(1,q):
                f1=0
print(pib)    
pub=key.kg(pib,a,q)
print()
print("public of bob",pub)
print("session key generated by alice",end=" ")
ska=key.kg(pia,pub,q)
print(ska)
print("session key generated by bob",end=" ")
skb=key.kg(pib,pua,q)
print(skb)
#print(format(skb,'010b'))
f=open("E:\python\cgns\S-DES\dfkeysend.txt","w")
f.write(str(format(ska,'010b')))
f.close()
f=open("E:\python\cgns\S-DES\dfkeyrec.txt","w")
f.write(str(format(skb,'010b')))
f.close()
